# read: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM Version
        run: npm -v

      - name: Install Dependencies
        run: npm install

      - name: Build Packages
        run: npm run build

  windows:
    needs: ubuntu

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM Version
        run: npm -v

      - name: Install Dependencies
        run: npm install

      - name: Build Packages
        run: npm run build
